#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v16
# autospec commit: b858a2a
#
Name     : fd
Version  : 10.1.0
Release  : 3
URL      : https://github.com/sharkdp/fd/archive/refs/tags/v10.1.0.tar.gz
Source0  : https://github.com/sharkdp/fd/archive/refs/tags/v10.1.0.tar.gz
Source1  : http://localhost/cgit/vendor/fd/snapshot/fd-2024-07-08-21-50-38.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause ICU MIT Unicode-DFS-2016 Unlicense
Requires: fd-license = %{version}-%{release}
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# fd
[![CICD](https://github.com/sharkdp/fd/actions/workflows/CICD.yml/badge.svg)](https://github.com/sharkdp/fd/actions/workflows/CICD.yml)
[![Version info](https://img.shields.io/crates/v/fd-find.svg)](https://crates.io/crates/fd-find)
[[中文](https://github.com/cha0ran/fd-zh)]
[[한국어](https://github.com/spearkkk/fd-kor)]

%package license
Summary: license components for the fd package.
Group: Default

%description license
license components for the fd package.


%prep
%setup -q -n fd-10.1.0
cd %{_builddir}
tar xf %{_sourcedir}/fd-2024-07-08-21-50-38.tar.xz
cd %{_builddir}/fd-10.1.0
mkdir -p ./vendor
cp -r %{_builddir}/fd-2024-07-08-21-50-38/* %{_builddir}/fd-10.1.0/./vendor
mkdir -p .cargo
echo '[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1721663875
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1721663875
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fd
cp %{_builddir}/fd-%{version}/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/145c01c826ab5757f9cf06ec5cc0317e28707d97 || :
cp %{_builddir}/fd-%{version}/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/e4a7727ada4a37e2410ace8f00749c6e8ee15563 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/fd/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/fd-2024-07-08-21-50-38/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/fd/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/android-tzdata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/db8bf4070b91bbabe0f14d1c15f0be86793fab6a || :
cp %{_builddir}/fd-2024-07-08-21-50-38/android-tzdata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/2c87153926f8a458cffc9a435e15571ba721c2fa || :
cp %{_builddir}/fd-2024-07-08-21-50-38/android_system_properties/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/a8ab3e6caa5e7af0ec9235d5db800ace830c0a38 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/android_system_properties/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ac0bf7546a377351144d930c5e31eff058fe4e8f || :
cp %{_builddir}/fd-2024-07-08-21-50-38/anstream/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/anstream/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/anstyle-parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/fd-2024-07-08-21-50-38/anstyle-parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/64a8c11fd0f3068e743bfc681bcbef4f50a6b779 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/anstyle-query/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/anstyle-query/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/anstyle-wincon/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/anstyle-wincon/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/33dbd2d99ad231460bbb01812a52c85e577bd9ba || :
cp %{_builddir}/fd-2024-07-08-21-50-38/anstyle/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/anstyle/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/f911b0506e6ba6a56b4edac717b461799f380ef0 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/anyhow/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/fd-2024-07-08-21-50-38/anyhow/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/argmax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/fd-2024-07-08-21-50-38/argmax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/43c5faf31028cf1286acc3f9d9d88b6290b6c383 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/fd-2024-07-08-21-50-38/bitflags-1.3.2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/bitflags-1.3.2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/bstr/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/bstr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/99b5dc64e06bf0354ef3baac0ea25c929e4e3a9a || :
cp %{_builddir}/fd-2024-07-08-21-50-38/bstr/src/unicode/data/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/fd/c4f8de16c29dc84a94d610b716fb1c9c7f143582 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/bumpalo/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/bumpalo/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/0a1e89ac22450cb0311baa2613bc21b7131b321f || :
cp %{_builddir}/fd-2024-07-08-21-50-38/cc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/cc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/cfg_aliases/LICENSE %{buildroot}/usr/share/package-licenses/fd/39806df76979277073594a0c19005c3c7fb17221 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/chrono/LICENSE.txt %{buildroot}/usr/share/package-licenses/fd/c145b1a607ecf06aed81f1d04a65c2e43dffdc63 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/clap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/clap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/clap_builder/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/fd-2024-07-08-21-50-38/clap_builder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/clap_complete/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/fd-2024-07-08-21-50-38/clap_complete/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/clap_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/fd-2024-07-08-21-50-38/clap_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/clap_lex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/fd-2024-07-08-21-50-38/clap_lex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/colorchoice/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/colorchoice/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/core-foundation-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/core-foundation-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/6c2945f449081ab19640fb7c70a081a1a4559399 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/crossbeam-channel/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/crossbeam-channel/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/crossbeam-deque/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/crossbeam-deque/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/crossbeam-epoch/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/crossbeam-epoch/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/crossbeam-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/crossbeam-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/ctrlc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/8bec88444202e13c35f17f3057132e6a21c287c1 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/ctrlc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/diff/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/fd-2024-07-08-21-50-38/diff/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/0db0557c9a1561fa3aa6693747121458bf7ddfcd || :
cp %{_builddir}/fd-2024-07-08-21-50-38/errno/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/errno/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/7a842f34e127456338641b14c7a00ec246d89fb6 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/etcetera/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/fd-2024-07-08-21-50-38/etcetera/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/faccess/LICENSE.txt %{buildroot}/usr/share/package-licenses/fd/78e0669746c99ca7a8d9cf322ac2e06daf16848c || :
cp %{_builddir}/fd-2024-07-08-21-50-38/fastrand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/fastrand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/filetime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/filetime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/globset/COPYING %{buildroot}/usr/share/package-licenses/fd/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/globset/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/fd-2024-07-08-21-50-38/globset/UNLICENSE %{buildroot}/usr/share/package-licenses/fd/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/fd-2024-07-08-21-50-38/home/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/1d47c63586fe3be7f228cff1ab0c029b53741875 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/home/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/humantime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/humantime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ff432d95fdfee3587e45abd61685c2209d245901 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/iana-time-zone-haiku/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/ff44b187892fcf1cd15a3ca61b498041b28afecc || :
cp %{_builddir}/fd-2024-07-08-21-50-38/iana-time-zone-haiku/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/d3f4001d9de83a122956c9195d73e2507bf6c533 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/iana-time-zone/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/ff44b187892fcf1cd15a3ca61b498041b28afecc || :
cp %{_builddir}/fd-2024-07-08-21-50-38/iana-time-zone/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/d3f4001d9de83a122956c9195d73e2507bf6c533 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/ignore/COPYING %{buildroot}/usr/share/package-licenses/fd/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/ignore/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/fd-2024-07-08-21-50-38/ignore/UNLICENSE %{buildroot}/usr/share/package-licenses/fd/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/is_terminal_polyfill/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/is_terminal_polyfill/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/jemalloc-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/jemalloc-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/jemalloc-sys/jemalloc/COPYING %{buildroot}/usr/share/package-licenses/fd/c797cef3f1b13a960a5119a084fb88529a924fd7 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/jemallocator/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/jemallocator/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/js-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/js-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/lazy_static/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/fd-2024-07-08-21-50-38/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/fd-2024-07-08-21-50-38/linux-raw-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/linux-raw-sys/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/fd/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/linux-raw-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/lscolors/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/fd-2024-07-08-21-50-38/lscolors/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/43c5faf31028cf1286acc3f9d9d88b6290b6c383 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/memchr/COPYING %{buildroot}/usr/share/package-licenses/fd/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/fd-2024-07-08-21-50-38/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/fd/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/nix-0.24.3/LICENSE %{buildroot}/usr/share/package-licenses/fd/a6fe1503554eb18138838c526d150f58fc104133 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/nix/LICENSE %{buildroot}/usr/share/package-licenses/fd/a6fe1503554eb18138838c526d150f58fc104133 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/normpath/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/a6a5418b4d67d9f3a33cbf184b25ac7f9fa87d33 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/normpath/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/086d6c321d4f9363125626e2f538dbb8c6e17d49 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/normpath/LICENSE-THIRD-PARTY %{buildroot}/usr/share/package-licenses/fd/e29634d5d70ede8d036df23414ea838e2cfdf0bd || :
cp %{_builddir}/fd-2024-07-08-21-50-38/nu-ansi-term/LICENSE %{buildroot}/usr/share/package-licenses/fd/fea05fa01bac661c706e9e134d9d80b2248bb065 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/num-traits/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/num-traits/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/fd-2024-07-08-21-50-38/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/fd-2024-07-08-21-50-38/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/fd/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/regex-automata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/regex-automata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/fd/68d12a03b339648117165b9c021b93f26974d6f6 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/rustix/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/rustix/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/fd/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/rustix/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/same-file/COPYING %{buildroot}/usr/share/package-licenses/fd/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/same-file/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/same-file/UNLICENSE %{buildroot}/usr/share/package-licenses/fd/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/fd-2024-07-08-21-50-38/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/fd-2024-07-08-21-50-38/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/strsim/LICENSE %{buildroot}/usr/share/package-licenses/fd/f5feee4154156527645a9b18ef29da23fc859ca9 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/fd-2024-07-08-21-50-38/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/tempfile/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/tempfile/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/70693ba8757c4a17af68e39ab32e4e0d4a389416 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/terminal_size/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/terminal_size/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/e08d1736c80198e1adec92ff27482e7abbc42d86 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/test-case-core/LICENSE %{buildroot}/usr/share/package-licenses/fd/8df5650b8e524271748bc56788559a75018d5842 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/test-case-macros/LICENSE %{buildroot}/usr/share/package-licenses/fd/8df5650b8e524271748bc56788559a75018d5842 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/test-case/LICENSE %{buildroot}/usr/share/package-licenses/fd/8df5650b8e524271748bc56788559a75018d5842 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/fd-2024-07-08-21-50-38/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/fd/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/utf8parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/fd-2024-07-08-21-50-38/utf8parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/93074692b8a28bef1743c44a9e5b97b1401c0d09 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/version_check/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/version_check/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/cfcb552ef0afbe7ccb4128891c0de00685988a4b || :
cp %{_builddir}/fd-2024-07-08-21-50-38/walkdir/COPYING %{buildroot}/usr/share/package-licenses/fd/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/walkdir/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/fd-2024-07-08-21-50-38/walkdir/UNLICENSE %{buildroot}/usr/share/package-licenses/fd/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/wasm-bindgen-backend/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/wasm-bindgen-backend/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/wasm-bindgen-macro-support/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/wasm-bindgen-macro-support/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/wasm-bindgen-macro/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/wasm-bindgen-macro/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/wasm-bindgen-shared/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/wasm-bindgen-shared/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/wasm-bindgen/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/wasm-bindgen/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/winapi-util/COPYING %{buildroot}/usr/share/package-licenses/fd/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/winapi-util/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/winapi-util/UNLICENSE %{buildroot}/usr/share/package-licenses/fd/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/winapi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fd/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/fd-2024-07-08-21-50-38/winapi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fd/2243f7a86daaa727d34d92e987a741036f288464 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows-core/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows-core/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows-sys-0.48.0/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows-sys-0.48.0/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows-sys/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows-sys/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows-targets-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows-targets-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_aarch64_gnullvm-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_aarch64_gnullvm-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_aarch64_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_aarch64_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_i686_gnu-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_i686_gnu-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_i686_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_i686_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_i686_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_i686_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_x86_64_gnu-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_x86_64_gnu-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_x86_64_gnullvm-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_x86_64_gnullvm-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_x86_64_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_x86_64_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/fd-2024-07-08-21-50-38/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fd/086d6c321d4f9363125626e2f538dbb8c6e17d49
/usr/share/package-licenses/fd/0a1e89ac22450cb0311baa2613bc21b7131b321f
/usr/share/package-licenses/fd/0db0557c9a1561fa3aa6693747121458bf7ddfcd
/usr/share/package-licenses/fd/144111aa0f14ef5a181326683aa9ebbd9252bca6
/usr/share/package-licenses/fd/145c01c826ab5757f9cf06ec5cc0317e28707d97
/usr/share/package-licenses/fd/1d47c63586fe3be7f228cff1ab0c029b53741875
/usr/share/package-licenses/fd/2243f7a86daaa727d34d92e987a741036f288464
/usr/share/package-licenses/fd/2ad1215c12bd0a3492399dc438aa63084323c662
/usr/share/package-licenses/fd/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
/usr/share/package-licenses/fd/2c87153926f8a458cffc9a435e15571ba721c2fa
/usr/share/package-licenses/fd/33dbd2d99ad231460bbb01812a52c85e577bd9ba
/usr/share/package-licenses/fd/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/fd/39806df76979277073594a0c19005c3c7fb17221
/usr/share/package-licenses/fd/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/fd/43c5faf31028cf1286acc3f9d9d88b6290b6c383
/usr/share/package-licenses/fd/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/fd/4dbe8833d0189c691b308c3dd40fab84ef2e9630
/usr/share/package-licenses/fd/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/fd/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/fd/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/fd/64a8c11fd0f3068e743bfc681bcbef4f50a6b779
/usr/share/package-licenses/fd/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/fd/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/fd/68d12a03b339648117165b9c021b93f26974d6f6
/usr/share/package-licenses/fd/6c2945f449081ab19640fb7c70a081a1a4559399
/usr/share/package-licenses/fd/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/fd/70693ba8757c4a17af68e39ab32e4e0d4a389416
/usr/share/package-licenses/fd/78e0669746c99ca7a8d9cf322ac2e06daf16848c
/usr/share/package-licenses/fd/7a842f34e127456338641b14c7a00ec246d89fb6
/usr/share/package-licenses/fd/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/fd/8bec88444202e13c35f17f3057132e6a21c287c1
/usr/share/package-licenses/fd/8df5650b8e524271748bc56788559a75018d5842
/usr/share/package-licenses/fd/8fe88f09d35c6054e0a780a793833c16fb888168
/usr/share/package-licenses/fd/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/fd/93074692b8a28bef1743c44a9e5b97b1401c0d09
/usr/share/package-licenses/fd/99b5dc64e06bf0354ef3baac0ea25c929e4e3a9a
/usr/share/package-licenses/fd/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/fd/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/fd/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/fd/a6a5418b4d67d9f3a33cbf184b25ac7f9fa87d33
/usr/share/package-licenses/fd/a6fe1503554eb18138838c526d150f58fc104133
/usr/share/package-licenses/fd/a8ab3e6caa5e7af0ec9235d5db800ace830c0a38
/usr/share/package-licenses/fd/ac0bf7546a377351144d930c5e31eff058fe4e8f
/usr/share/package-licenses/fd/c145b1a607ecf06aed81f1d04a65c2e43dffdc63
/usr/share/package-licenses/fd/c4f8de16c29dc84a94d610b716fb1c9c7f143582
/usr/share/package-licenses/fd/c797cef3f1b13a960a5119a084fb88529a924fd7
/usr/share/package-licenses/fd/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/fd/cfcb552ef0afbe7ccb4128891c0de00685988a4b
/usr/share/package-licenses/fd/d3f4001d9de83a122956c9195d73e2507bf6c533
/usr/share/package-licenses/fd/db8bf4070b91bbabe0f14d1c15f0be86793fab6a
/usr/share/package-licenses/fd/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/fd/e08d1736c80198e1adec92ff27482e7abbc42d86
/usr/share/package-licenses/fd/e29634d5d70ede8d036df23414ea838e2cfdf0bd
/usr/share/package-licenses/fd/e4a7727ada4a37e2410ace8f00749c6e8ee15563
/usr/share/package-licenses/fd/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/fd/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/fd/f5feee4154156527645a9b18ef29da23fc859ca9
/usr/share/package-licenses/fd/f911b0506e6ba6a56b4edac717b461799f380ef0
/usr/share/package-licenses/fd/fea05fa01bac661c706e9e134d9d80b2248bb065
/usr/share/package-licenses/fd/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
/usr/share/package-licenses/fd/ff432d95fdfee3587e45abd61685c2209d245901
/usr/share/package-licenses/fd/ff44b187892fcf1cd15a3ca61b498041b28afecc
